### ISSUE TITLE
Nexus 5, linux-image-3.4.0-1-hammerhead - looking for Kernel update

### ISSUE THREAD

**Issue by ravikv123** [masneyb/nexus-5-upstream#1]
Hi..
Im running linux ubuntu touch on Nexus 5, getting the below error whn trying to install docker
**time="2019-10-26T22:13:52.045791393+05:30" level=fatal msg="Your Linux kernel version 3.4.0-cyanogenmod-gc95a726 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer."**
Looking at your project, any luck in upgrading the kernel to anything higher than 3.10.0? 
raised [Request](https://github.com/ubports/ubuntu-touch/issues/1276) in ubuntu touch. but i doubt any one has updated kernel
Thankyou..

**Comment by masneyb** [comment]
I've used Docker on my Nexus 5 with an upstream kernel for a presentation around this time last year. I haven't tested this since last year, but you'll need to add the following lines to arch/arm/configs/qcom_defconfig when building the upstream kernel in order to get Docker working:

```
CONFIG_IP_NF_IPTABLES=y
CONFIG_NETFILTER_XTABLES=y
CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y
CONFIG_NF_CONNTRACK=y
CONFIG_TASK_IO_ACCOUNTING=y
CONFIG_TASKSTATS=y
CONFIG_TASK_DELAY_ACCT=y
CONFIG_SECCOMP=y
CONFIG_IPVLAN=y
CONFIG_VXLAN=y
CONFIG_IP_NF_NAT=y
CONFIG_NETFILTER=y
CONFIG_NETFILTER_XT_MATCH_IPVS=y
CONFIG_NET_NS=y
CONFIG_PID_NS=y
CONFIG_IPC_NS=y
CONFIG_UTS_NS=y
CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
CONFIG_MACVLAN=y
CONFIG_VETH=y
CONFIG_BRIDGE_NETFILTER=y
CONFIG_NF_NAT_IPV4=y
CONFIG_IP_NF_FILTER=y
CONFIG_IP_NF_TARGET_MASQUERADE=y
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
CONFIG_NF_NAT=y
CONFIG_NF_NAT_NEEDED=y
CONFIG_POSIX_MQUEUE=y
CONFIG_MEMCG_SWAP=y
CONFIG_MEMCG_SWAP_ENABLED=y
CONFIG_RESOURCE_COUNTERS=y
CONFIG_IOSCHED_CFQ=y
CONFIG_CGROUP_PERF=y
CONFIG_CFS_BANDWIDTH=y
CONFIG_AUFS_FS=y
CONFIG_DM_THIN_PROVISIONING=y
CONFIG_OVERLAY_FS=y
```
I'm not sure what it would take to integrate the newer kernel with Ubuntu touch. Be aware though that the upstream kernel won't support all of the features on the phone like the modem, sound, etc. The display, touchscreen, and some of the peripherals will work.

postmarketOS uses the upstream kernel, plus some of my out-of-tree patches for the GPU, for the Nexus 5, so you can use that. Their kernel in that project doesn't include the config options I listed above.
