### ISSUE TITLE
Mainline kernel's image is too large to boot

### ISSUE THREAD

**Issue by nfraprado** [masneyb/nexus-5-upstream#7]
With kernel 5.7.6 I was able to boot using the `build-kernel` script, but on more recent kernels up to the mainline, the qcom_defconfig used causes too much to be enabled (I think it's those media configs, like `DIGITAL_TV`), making the image too large (a bit over 100MB), and even though there's no error during flashing, there's no output on the console after fastboot.

By enabling [one option in the config](https://gitlab.com/nfraprado/linux/-/commit/2d024e08b3c26b307c4d1111981599e6b4038f1d), others are disabled by default, and brings the image back to 80MB or so, which boots successfully.

I'm not sure what to do about this. I did try the postmarketOS image and they're on 5.9, with `DIGITAL_TV` enabled and it still works, although I think the flashing process is different there.

**Comment by masneyb** [comment]
I use a slightly different flashing process than what postmarketOS uses. Mainly, I embed the modules and kernel together in a single image to make it much easier to quickly reflash the device. In the initrd, there's a copy-to-root-fs directory that contains the modules and other files to copy. I didn't want to reflash the userspace partition each time since that's pretty slow.

I can have the `build-kernel` script emit a warning if the boot image is too large and `CONFIG_MEDIA_SUPPORT_FILTER` is not enabled.

**Comment by nfraprado** [comment]
Oh, I didn't realize that. Yeah, it makes sense to avoid reflashing userspace and keep it fast.

Yeah, I think a warning when the boot image is too large would always be useful. "Try enabling `CONFIG_MEDIA_SUPPORT_FILTER` if it isn't already" could be a useful tip to be printed together with that warning, but only as a tip, as that won't always be the reason for big images (and I'm not even sure it's the best way to counter it), but would work for the common case.

**Comment by masneyb** [comment]
I pushed up a change to build-kernel with the `CONFIG_MEDIA_SUPPORT_FILTER` hint.
